# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi

# User specific environment and startup programs
JAVA_HOME=/usr/java/latest
JAVA_OPTS=
ANT_OPTS="-Xmx2g -XX:MaxPermSize=256m"
MAVEN_OPTS="-Xmx2g -XX:MaxPermSize=256m"
PATH=$PATH:$HOME/.local/bin:$HOME/bin

export PATH JAVA_HOME JAVA_OPTS ANT_OPTS MAVEN_OPTS
